const actionType = {
    GET_HOME: "GET_HOME",
    SET_CUR_MUSIC: "SET_CUR_MUSIC",
    LOADING: "LOADING",

    SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
    SET_CUR_PLAYLIST_DATA: "SET_CUR_PLAYLIST_DATA",
    SET_RECENT: ' SET_RECENT',


    //Music
    PLAY_MUSIC: "PLAY_MUSIC",
    SET_ALBUM: "SET_ALBUM",
    PLAY_LIST: "PLAY_LIST"
}

export default actionType;